services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8800:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db 

  db:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: {}

