version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8800:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db 

  db:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
   mysql_data: {}
