# Dockerfile-web
FROM php:8.3-apache

# Install dependencies and the MySQLi extension
RUN apt-get update && \
    apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd mysqli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Copy the source code to the Apache document root
COPY ./src /var/www/html/

# Set permissions for the web root
RUN chown -R www-data:www-data /var/www/html
